### ISSUE TITLE
Feature Idea: Adding rotating backgrounds

### ISSUE THREAD

**Issue by nslee333** [bend-devops/bend-devops.github.io#1]
Brian and I had an idea to rotate the site's background with a few images that I've found.

It should be fairly easy, upload the background images, and have a JS script that randomly chooses what image to use.

It'd be a straight-forward PR for @MrKomputerKid if he's interested, I don't have the time currently to add this feature.

**Comment by MrKomputerKid** [comment]
I just saw this, yes I can tackle this!

**Comment by MrKomputerKid** [comment]
Hi all, I just submitted a pull request, please see: [PR #2](https://github.com/bend-devops/bend-devops.github.io/pull/2)

**Comment by nslee333** [comment]
Resolved with PR #2
